### ISSUE TITLE
Error on running: you are using an empty matrix - Eigen

### ISSUE THREAD

**Issue by deathlyhallows010** [AlbertoJaenal/L1Homotopy_cpp#1]
While testing the test_MATLAB.cpp
The following error was encountered.

Assertion failed: this->rows()>0 && this->cols()>0 && "you are using an empty matrix", file ..\eigen\Eigen\src\Core\Visitor.h, line 251

**Comment by AlbertoJaenal** [comment]
Hi, @deathlyhallows010 

I checked the repo installing it from raw and it works perfectly on my PC. Without more info, I cannot help you, but it seems like the _readCSV_ functions could not be working properly. You can check if the A, x and b are correctly read.

**Comment by deathlyhallows010** [comment]
Hey @AlbertoJaenal 
I have checked the readCSV function function, Its perfectly loading the A, x and b matrix. 
But still I am encountering the error below:

/tmp/cc8XMMsW.o: In function `DSHomotopy::DSHomotopy(double, int, bool)':
test_MATLAB.cpp:(.text._ZN10DSHomotopyC2Edib[_ZN10DSHomotopyC5Edib]+0x29): undefined reference to `vtable for DSHomotopy'
/tmp/cc8XMMsW.o: In function `BPDNHomotopy::BPDNHomotopy(double, int, bool)':
test_MATLAB.cpp:(.text._ZN12BPDNHomotopyC2Edib[_ZN12BPDNHomotopyC5Edib]+0x29): undefined reference to `vtable for BPDNHomotopy'
collect2: error: ld returned 1 exit status

**Comment by AlbertoJaenal** [comment]
Yes, I've been researching and it seemed to be problems derived from not implementing non-pure virtual functions. I've pushed a new commit solving it, check if the solution works for you.

**Comment by deathlyhallows010** [comment]
I think we need to make sure that all the non-pure virtual functions have an implementation.

**Comment by deathlyhallows010** [comment]
No it still shows the same error. I think it due to some other situation,

**Comment by AlbertoJaenal** [comment]
Can you send the the system properties and the compiler/libraries versions?

**Comment by deathlyhallows010** [comment]
Thanks the problem with the implementing non-pure virtual functions is solved.

But coming to my first issue, while running the code. After initial Initiazation the following error occurs 

	

> Primal Add 161!	Dual Add 161!
> Initialization: 0.00333
> BPDN_homotopy: /usr/include/eigen3/Eigen/src/Core/DenseBase.h:257: void Eigen::DenseBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; Eigen::Index = long int]: Assertion `rows == this->rows() && cols == this->cols() && "DenseBase::resize() does not actually allow one to resize."' failed.

**Comment by AlbertoJaenal** [comment]
Could you describe how did you solve the non-pure virtual functions implementation?

What is your Eigen3 version? What is your compiler version? Your initialization takes 30 times longer than mine (_Initialization: 0.00011_)

Without more info, I can't help you. The resize error seems to be a mismatch for EIgen3 versions.

**Comment by deathlyhallows010** [comment]
I am using g++  4:7.3.0-3ubuntu2.1  amd64 GNU C++ compiler
Eigen3 version 3.3.4
Can you provide me the Eigen version you are using.
- Thanks

**Comment by AlbertoJaenal** [comment]
Practically the same, I'm using g++ 7.4.0 and Eigen3 3.3.7.

The only thing I can say you at this point is to assure that you are using the Eigen3 3.3.4, maybe the compiler is using another one previously installed (https://github.com/libigl/libigl/issues/425).

Meanwhile, I'll try to run the code in a partner's computer to see if the error also occurs.

**Comment by deathlyhallows010** [comment]
Hi @AlbertoJaenal 

In BPDN_homotopy.cpp Line No: 192
`AtAgx_mod.block(0, 0, gamma_x.size(), gamma_xk.size()) = AtgxAnx; // AtAgx_mod 11`

.block() is not able to change AtAgx_mod of type MatrixXd, which in turn throws the previous error.
`void Eigen::DenseBase<Derived>::resize(Eigen::Index, Eigen::Index) [with Derived = Eigen::Block<Eigen::Matrix<double, -1, -1>, -1, -1, false>; Eigen::Index = long int]: Assertion rows == this->rows() && cols == this->cols() && "DenseBase::resize() does not actually allow one to resize."' failed`

Here is what I want to say
   ```
Eigen::MatrixXd m(3,3);
   m << 1,2,3,
       4,5,6,
       7,8,9;
  m.block(0,0,1,2) = 99 // Compiler Error;
```

**Comment by AlbertoJaenal** [comment]
So, the problem is that the MatrixXd does not allow block operations (both in my code and in the test code you wrote)?

If that is the situation, it's strange. Seems to be a problem on your pc. As I said in the previous post, ensure that you are using the Eigen 3.3 version (you may have another one compiled in the shadow and the cmake may be using that). Force the 3.3 library in the project making or reinstall the library. I cannot help you from now, because that seems to be a problem on your pc.

**Comment by deathlyhallows010** [comment]
Even tried this on a online compiler https://godbolt.org/z/LsjWuf
Its really strange why it didn't worked for me. By the way thanks for your  time.

**Comment by AlbertoJaenal** [comment]
Try adding 

#include <Eigen/Dense>

**Comment by deathlyhallows010** [comment]
Nope

**Comment by AlbertoJaenal** [comment]
Seems to be an error due to the including form.

When I compile the project through cmake, I got no problem, but if I compile:
`g++  -I/usr/include/eigen3  file.cpp -o output`
it does not work (is how the online compiler does it). Probably a problem due to alignments or versions.

Are you compilig the project with the cmake I supplied?

**Comment by deathlyhallows010** [comment]
Yup It works perfectly fine using `cmake`. Earlier I was using `g++ test_file.cpp` directly. I am quite new to cpp so can you explain what went wrong. 
-Thanks

**Comment by AlbertoJaenal** [comment]
Hi @deathlyhallows010 

finally, I found what was happening. The main addition that compiling through `cmake` makes is the flag `-DNDEBUG`. As commented [here](https://stackoverflow.com/a/24257232), this flag turn off C asserts, which are the ones raised while performing `.block()` operations in this case. With this flag , it worked even in the online compiler that you shared with me. I included some additional flags:
`g++ -I/usr/include/eigen3 -std=c++11  -DNDEBUG  -rdynamic file.cpp -o output`

I am not so skilled with C++, so I had to google a lot until I found this. However, this is not a forum for C++ doubts, this is a forum for issues with this repository. As you said me, the compilation with `cmake` that I posted worked fine for you, the problem was with a specific compilation for your specific case. Next time, consider asking in specific C++ forums as Stack Overflow or so. 
Anyway, I was curious about the difference between both compilations and it helped me grow as a programmer.

I understand I can close this issue, so I'm closing it.

Have a great time with BPDN!
